version: 2
jobs:
  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      TERM: dumb
      MAVEN_OPTS: "-Xmx512m"
    docker:
      - image: circleci/jdk8:0.1.1
      - image: maven:3.3.9
    steps:
      - checkout
      - run:
          name: Compile Only
          command: mvn install -DskipTests=true -B
  test:
    docker:
      - image: circleci/java:8
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn surefire:test -B
      - run: mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run: find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - run: find . -type f -regex ".*/target/surefire-reports/.*-output.txt" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - store_artifacts:
          path: "gosu-test/target/site"
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /rel\/.*/
      - test:
          requires:
            - build
