version: 2
jobs:
  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      TERM: dumb
      MAVEN_OPTS: "-Xmx512m"
    docker:
      - image: circleci/java:8
    steps:
      - checkout
      - run: mvn -version
      - run:
          name: Compile Only
          command: mvn install -DskipTests=true -B
      - run:
          name: Run tests
          command: mvn install surefire:test -B
      - run: sudo mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run: sudo find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - run: sudo find . -type f -regex ".*/target/surefire-reports/.*-output.txt" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - store_artifacts:
          path: "gosu-test/target/site"
  test:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      TERM: dumb
      MAVEN_OPTS: "-Xmx512m"
    docker:
      - image: circleci/java:8
    steps:
      - checkout
      - run: mvn -version
      - run:
          name: Run tests
          command: mvn install surefire:test -B
      - run: sudo mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run: sudo find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - run: sudo find . -type f -regex ".*/target/surefire-reports/.*-output.txt" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - store_artifacts:
          path: "gosu-test/target/site"
  deploy:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      TERM: dumb
      MAVEN_OPTS: "-Xmx512m"
    docker:
      - image: circleci/java:8
    steps:
      - checkout
      - run:
          name: deploy 
          command: ./ci_scripts/deploy_snapshot.sh
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /rel\/.*/
     # - test:
     #     requires:
     #       - build
      - deploy:
          requires:
            - build
                #filters:
                 # branches:
                   # ignore:
                     # - /^(?rel\/).+/
