version: 2
jobs:
  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      TERM: dumb
      MAVEN_OPTS: "-Xmx1024m"
      TEST_REPORTS_DIR: "/tmp/test-results"
    machine:
      image: circleci/classic:latest
    branches:
      ignore:
        - /rel\/.*/
    steps:
      - checkout
      - restore_cache:
          key: v1-test-{{ checksum "gosu-parent/pom.xml" }}
      - run:
          name: Run tests
          command: mvn test -B
      - run:
          name: Create test metadata folder
          command: sudo mkdir -p ~/junit/
      - run:
          name: Collect test metadata
          command: sudo find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
      - run:
          name: Collect test stdout
          command: sudo find . -type f -regex ".*/target/surefire-reports/.*-output.txt" -exec cp {} ~/junit/ \;
      - run:
          command: ls -l ~/junit/
      - deploy:
          command: ./ci_scripts/deploy_snapshot.sh
      - store_artifacts:
          path: ~/junit
      - store_test_results:
          path: ~/junit
      - save_cache:
          key: v1-test-{{ checksum "gosu-parent/pom.xml" }}
          paths:
            - ~/.m2
